### ISSUE TITLE
Correct SendGrid API link

### ISSUE THREAD

**Issue by antononcube** [jnthn/raku-email-sendgrid#2]
I think the correct link in the README.md file for SendGrid API should be:

https://docs.sendgrid.com/for-developers/sending-email/api-getting-started 

(Not https://sendgrid.com/docs/API_Reference/api_v3.html . )

Here is the correction I suggest:

```markdown
[SendGrid Web API (v3)](https://docs.sendgrid.com/for-developers/sending-email/api-getting-started)
```

**Comment by lizmat** [comment]
Link updated.
